export const LOGIN_START = 'LOG_IN_START';
export const LOGIN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOGIN_FAILED = 'LOG_IN_FAILED';
export const LOGIN_INVALID_DATA = 'LOG_IN_INVALID_DATA';
export const LOGOUT = 'LOG_OUT';

export const ENABLE_GREETING = 'ENABLE_GREETING';
export const DISABLE_GREETING = 'DISABLE_GREETING';
