export const USER_LOG_IN_REQUEST_START = 'USER_LOG_IN_REQUEST_START';
export const USER_LOG_IN_REQUEST_SUCCESS = 'USER_LOG_IN_REQUEST_SUCCESS';
export const USER_LOG_IN_REQUEST_FAILED = 'USER_LOG_IN_REQUEST_FAILED';
export const USER_LOG_IN_REQUEST_INVALID_DATA = 'USER_LOG_IN_REQUEST_INVALID_DATA';
