export const FORGOT_PASSWORD_REQUEST_START = 'FORGOT_PASSWORD_REQUEST_START';
export const FORGOT_PASSWORD_REQUEST_SUCCESS = 'FORGOT_PASSWORD_REQUEST_SUCCESS';
export const FORGOT_PASSWORD_REQUEST_ERROR = 'FORGOT_PASSWORD_REQUEST_ERROR';
