export const SET_USER_INFO = 'SET_USER_TOKEN';
export const RESET_USER_INFO = 'RESET_USER_TOKEN';
export const SYNC_USER_INFO = 'SYNC_USER_TOKEN';

export const CHECK_EMAIL_EXISTENCE_START = 'CHECK_EMAIL_EXISTENCE_START';
export const CHECK_EMAIL_EXISTENCE_SUCCESS = 'CHECK_EMAIL_EXISTENCE_SUCCESS';
export const CHECK_EMAIL_EXISTENCE_ERROR = 'CHECK_EMAIL_EXISTENCE_ERROR';
