// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RedTeam.TechArtSurvey.Repositories.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201707131712384_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
