export const SEND_SURVEY_START = 'SEND_SURVEY_START';
export const SEND_SURVEY_SUCCESS = 'SEND_SURVEY_SUCCESS';
export const SEND_SURVEY_ERROR = 'SEND_SURVEY_ERROR';
export const GET_SURVEY_START = 'GET_SURVEY_START';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_ERROR = 'GET_SURVEY_ERROR';