export const CHECK_PASSWORD_RESET_TOKEN_START = 'CHECK_PASSWORD_RESET_TOKEN_START';
export const CHECK_PASSWORD_RESET_TOKEN_SUCCESS = 'CHECK_PASSWORD_RESET_TOKEN_SUCCESS';
export const CHECK_PASSWORD_RESET_TOKEN_ERROR = 'CHECK_PASSWORD_RESET_TOKEN_ERROR';
