export const CHECK_PASSWORD_RESET_TOKEN_START = 'CHECK_PASSWORD_RESET_TOKEN_START';
export const CHECK_PASSWORD_RESET_TOKEN_SUCCESS = 'CHECK_PASSWORD_RESET_TOKEN_SUCCESS';
export const CHECK_PASSWORD_RESET_TOKEN_ERROR = 'CHECK_PASSWORD_RESET_TOKEN_ERROR';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
