export const CREATE_SURVEY_START = 'CREATE_SURVEY_START';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const CREATE_SURVEY_FAILED = 'CREATE_SURVEY_FAILED';
export const CREATE_SURVEY_INVALID_DATA = 'CREATE_SURVEY_INVALID_DATA';