export const questionTypes = {
  SINGLE_ANSWER : 'SINGLE_ANSWER',
  MULTIPLE_ANSWER : 'MULTIPLE_ANSWER',
  FILE_ANSWER : 'FILE_ANSWER',
  TEXT_ANSWER : 'TEXT_ANSWER',
  STAR_RATING_ANSWER : 'STAR_RATING_ANSWER',
  SCALE_RATING_ANSWER : 'SCALE_RATING_ANSWER',
};

export const defaultType = questionTypes.SINGLE_ANSWER;