export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_INVALID_DATA = 'SIGN_UP_INVALID_DATA';

export const CHECK_EMAIL_EXISTENCE_START = 'CHECK_EMAIL_EXISTENCE_START';
export const CHECK_EMAIL_EXISTENCE_SUCCESS = 'CHECK_EMAIL_EXISTENCE_SUCCESS';
export const CHECK_EMAIL_EXISTENCE_ERROR = 'CHECK_EMAIL_EXISTENCE_ERROR';
