export const REACT_BOOTSTRAP_VALIDATION_STATE_SUCCESS = 'success';
export const REACT_BOOTSTRAP_VALIDATION_STATE_ERROR = 'error';

export const USER_NAME_MIN_LENGTH = 5;
export const USER_PASSWORD_MIN_LENGTH = 8;

export const COMMON_TITLE_REQUIRED_ERROR_ID = 'COMMON_TITLE_REQUIRED_ERROR_ID';

export const USER_NAME_REQUIRED_ERROR_ID = 'USER_NAME_REQUIRED_ERROR_ID';
export const USER_NAME_MIN_LENGTH_ERROR_ID = 'USER_NAME_MIN_LENGTH_ERROR_ID';
export const USER_EMAIL_REQUIRED_ERROR_ID = 'USER_EMAIL_REQUIRED_ERROR_ID';
export const USER_EMAIL_INCORRECT_ERROR_ID = 'USER_EMAIL_INCORRECT_ERROR_ID';
export const USER_PASSWORD_REQUIRED_ERROR_ID = 'USER_PASSWORD_REQUIRED_ERROR_ID';
export const USER_PASSWORD_MIN_LENGTH_ERROR_ID = 'USER_PASSWORD_MIN_LENGTH_ERROR_ID';
export const USER_CONFIRMATION_PASSWORD_MUST_MATCH_ERROR_ID = 'USER_CONFIRMATION_PASSWORD_MUST_MATCH_ERROR_ID';

export const QUESTION_TITLE_REQUIRED_ERROR_ID = 'QUESTION_TITLE_REQUIRED_ERROR_ID';
