export const GET_SURVEY_START = 'GET_SURVEY_START';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_ERROR = 'GET_SURVEY_ERROR';
export const SEND_RESPONSE_START = 'SEND_RESPONSE_START';
export const SEND_RESPONSE_SUCCESS = 'SEND_RESPONSE_SUCCESS';
export const SEND_RESPONSE_ERROR = 'SEND_RESPONSE_ERROR';
