export const GET_SURVEYS_START = 'GET_SURVEYS_START';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const GET_SURVEYS_ERROR = 'GET_SURVEYS_ERROR';
export const GET_SURVEYS_FILTER = 'GET_SURVEYS_FILTER';
export const SURVEYS_CLEAN = 'SURVEYS_CLEAN';
